### ISSUE TITLE
ibBTC Multisig Avatar

### ISSUE THREAD

**Issue by sajanrajdev** [Badger-Finance/badger-avatars#1]
Create an avatar to handle the actions currently performed by the [ibBTC multisig](https://etherscan.io/address/0xB76782B51BFf9C27bA69C77027e20Abd92Bcf3a8). These actions include:
- Claiming rewards (Takes in the merkle proof that could be fetched from Badger's API). This function could be written in such a way that it can be called permissionessly or, if found to be unsafe, by a predefined keeper and the owner.
- Processing rewards (These can take many different forms so using the open `call()` function should be sufficient for now.

The ibBTC multisig has the same owners as TechOps so the Avatar could be owned by TechOps (Or if found more appropiate, by Trops).

Include any appropriate tests!

**Comment by gosuto-inzasheru** [comment]
@sajanrajdev can you add this to the megaboard project? im migrating the msig board but i dont have the perms here.

**Comment by gosuto-inzasheru** [comment]
closing now that ibbtc is being deprecated. see https://github.com/Badger-Finance/badger-multisig/issues/993

**Comment by gosuto-inzasheru** [comment]
oh lol i am not powerful enough to close... @sajanrajdev?
