### ISSUE TITLE
AURA TCL Harvesting avatar

### ISSUE THREAD

**Issue by petrovska-petro** [Badger-Finance/badger-avatars#2]
# Avatar Review

The avatar will hold uniquely two BPT positions representing treasury TCL in *80BADGER_20WBTC* and *40WBTC_40DIGG_20GRAVIAURA* which will be staked into Aura.

The avatar needs to be capable of processing with a weekly cadence the rewards with the desired processing split, which are governed by `vault_msig`, allowing the msig setting up when appropriate different splits (e.g: 40/60, 70/30). Goal is that this action is run by CL keepers under the weekly cadence and process, at the moment, as follow:

1. BAL rewards: 70% is sold for USDC thru cowswap with the `vault_msig` as destination and the other 30% is dogfooded into our [bauraBAL sett](https://github.com/Badger-Finance/badger-multisig/blob/main/helpers/addresses.py#L279)

2. AURA rewards: 70% is sent to the `voter_msig` and 30% is sold for USDC thru cowswap with `vault_msig` as destination.

3. Since we're dogfooding into our sett, there will be *graviAURA* claimable in the tree, which needs to be claim and sent to the `vault_msig`. Worth exploring if [CL cron keepers](https://docs.chain.link/docs/jobs/) are capable of given an endpoint of claiming thru the avatar similarly with the weekly cadence to be in sync with the rest of claims from Aura staked bpt tokens.

The avatar should emit events for the tx-splits to easy track figures later on dashboards or similar tooling.

If possible, the avatar should have available methods to read how much is claimable at current `block.timestamp` and read how many funds are deposited in each bpt in aura if possible expressed in the underlying.

# Production iteration process

Since, this is likely to become the first avatar to production and will carry over the TCL responsibility, which represents a substantial dollar value. I recommend to have a test-production phase where it only holds max of 20% of what our TCL represents nowadays for these two bpts tokens in Aura. For the phase where all funds are delegated to this avatar to carry these operations and removing msig chores completely will advise for the following:

1. During test-production msig, SC and treasury pod are tracking and verifying that everything is going as expected

2. Have set a dashboard which can track all these actions which were carried by the avatar for tx exploring.

3. Tracker of performance of the avatar in place.

5. If all pods gives green light proceed topping up with funds to reach 100%.

# Resources 

[miro board](https://miro.com/app/board/uXjVOjIBGlw=/)

# Authorization

The ideation of this avatar when thru a treasury decision, with a positive majority. 

<img width="815" alt="Screenshot 2022-07-29 at 11 15 05" src="https://user-images.githubusercontent.com/84875062/181727112-4d6dd54b-46e5-4581-8c83-bfca99384958.png">

**Comment by petrovska-petro** [comment]
## 10th Aug sync summary

- for the simplification of the handling of `bauraBAL` decided to leverage `depositFor(vault)`  where tree claims can happen at convenient time, without the need of over-complexifying that automatisation in the avatar level, risks of cycles mismatching etc

- swaps between aura -> weth and bal -> weth. would use the following pools from Balancer, which one is highly incentivized by Aura and the other represents a key element for *veBAL* so liquidity is plenty for the sizes predicated by the TCL positions. [BAL-WETH](https://app.balancer.fi/#/pool/0x5c6ee304399dbdb9c8ef030ab642b10820db8f56000200000000000000000014) & [AURA-WETH](https://app.balancer.fi/#/pool/0xcfca23ca9ca720b6e98e3eb9b6aa0ffc4a5c08b9000200000000000000000274)

- confirmed with Aura team that this [pool](https://app.balancer.fi/#/pool/0xc29562b045d80fd77c69bec09541f5c16fe20d9d000200000000000000000251) is POL. This pool is of type *WeightedPool2Tokens*, which includes oracle features for pricing. In lack of CL oracle, we will leverage this oracle from this pool to establish reasonable min amount of the swap between aura -> weth. Reference to [docs](https://docs.balancer.fi/products/oracles?q=oracle#overview)

- for pricing of BAL and WETH there is existent CL oracles . [BAL](https://data.chain.link/ethereum/mainnet/crypto-usd/bal-usd) & [ETH](https://data.chain.link/ethereum/mainnet/crypto-usd/eth-usd)

- in light of [documentation](https://dev.balancer.fi/resources/query-batchswap-join-exit#warning) suggestions, advisable to leverage oracles mentioned above for the quote min amount purpose

**Comment by petrovska-petro** [comment]
## 17th Aug sync summary

- add standard events for facilitating revenue and claim metric analysis from finops pov at the avatar granularity

- suggestions around [gelato network](https://medium.com/gelato-network/gelato-network-integrates-flashbots-offering-web3-developers-front-running-protection-and-64e780ba6ce) for their offering of flashbots for keepers vs CL keepers for the code block pertenaiting the swaps vs tight slippage check with the external oracle calculations

- avatar expects receiving naked bpt's from the vault_msig (vanilla erc20 transfer) and process them via `deposit()` method to interact with the booster pointing to the right PID

- setting up infinity approvals carries any risk in the initialization?. only approves booster and despite of inheriting `call` from the base avatar should not add layer risk, since at the booster level there is no `depositFor` which can become a threat if multisig is exposed, so only will deposit in behalf of the avatar itself

- addition of view methods to explore avatar holdings and pending rewards claimable

- research regarding the best outcome between swapping bpt -> auraBAL vs leveraging the wrapper. Compare outcomes in different blocks and share in gsheet and gas comparison of adding this calculations on chain for the stable pool

**Comment by petrovska-petro** [comment]
simulations of the outcome via swap in the [stable pool](https://etherscan.io/address/0x3dd0843A028C86e0b760b1A76929d1C5Ef93a2dd):

- [gist](https://gist.github.com/petrovska-petro/63fe639c52ea38c0046c907bf90ec8a4)

- [sheet with values](https://docs.google.com/spreadsheets/d/1NKmMfcqfs_dDsAM9zxp1mdhvOT7IAvtOt1M3hmrygwY/edit#gid=1714513422)

**Comment by petrovska-petro** [comment]
simulations for comparing the min amount expected leverages the internal pool and CL oracles:

- [gist](https://gist.github.com/petrovska-petro/7a3c419be625a7a80707c7c997e2ec87)

- [sheet with oracle values VS querybatch](https://docs.google.com/spreadsheets/d/1KZe9-mcQvwcGU29E-cJjr__XZZWQhvaFkqGHLdOhx54/edit#gid=0)

**Comment by petrovska-petro** [comment]
## 24th Aug sync summary 

- reach the conclusion of adding the source and block number within the event itself is redundant, since they can be deducted from [eth_getLogs](https://www.quicknode.com/docs/ethereum/eth_getLogs)

- concluded on adding roles, so other entity (e.g: techops) can be used as a backup for block situation, where perhaps swaps may not meet the min rates given by the oracles and block the processing of rewards. It will have limited access to methods, which do not add any rugability, just easen up the process VS the 5/n signs expected to get in the vault

- move cadence to storage variable for adding flexibility, in case treasury decides to update it

- include events on deposit & withdrawal 

- leverage `transferFrom` in the *deposit* method, so not funds lives in the avatar itself. needs only approvals from the vault itself for specific amount targeted as deposit on the bpts

- beat time of CL keepers checks staleness up to 24H and bal/usd has deviation of 2% or 86400 seconds past from last answer

- discussed concerns on big deviation from current spot price during queries of the twap price, in case that in the latest hour prices run down or up massively, could trigger revert due to the *min* amounts calc thru those mechanism. will need to be resolved thru backup role to solve the situation 

- touched the reason on why `delegatcall` is added on the base of the avatar, is it required?. conclusion it's that in this case compared to the gnosis safe may not be required, also opens concerns/threats on the storage itself

- should we open up a bit more the slippage variable for the swaps, since we're leveraging external sources to determine the min amount expected?. currently on 98.25% (sim shows that in some instances may revert and 98% will be less likely).  But, if it is too tight, increases the chances on tx reverting, while if it too wide we may get worst rate and increase the MEV opp

- proceed to open the PR to loop in @sajanrajdev for an overall review of the contract for DD and review of test added, in case that some key test may be missing

**Comment by petrovska-petro** [comment]
## 1st Sept sync summary

- leave interface for keeper dual-compatibility, meaning we can leverage CL & Gelato with the same methods. CL needs to follow a compatibility interface standard, while gelato does not require that

- since keeper has setter method we can move from gelato to CL if necessary. mainly targeting gelato integration since they have flashbot feature, we'd register via UI. In theory, via UI automatically by default it uses flashbot fast mode. Also, we're in contact with Gelato in case that by default it is not using private tx, we can contact them for whitelisting given our task id/contract address

- allow twap variable to be a setter

- split staleness constants per CL oracle, one of them has 1H (eth/usd) vs 24H (bal/usd)

- clean-up some unused variables, saving bit of gas

- include natspec comments all around contract to facilitate context of each method and helps review process

- hand-over code review to Watchpug

**Comment by petrovska-petro** [comment]
## 8th Sept sync summary 

- discussed suggestions from hacknote and decided to into the suggestion of the off-chain estimate for the swaps, which will be pass later on as calldata into the perform up keep function

- communicate with cl  & gelato if they will be okay supporting calls in the checker method to non-view internal methods

- leverage *MAX* between off-chain slippage input and on-chain twap in the contract

- remove twap dependency in the bal -> bpt swap, try to instead leverage the invariant  and total supply

- concerns with timing of deployment regarding the possible gauge migrations, still good exercise for deployment & testing regardless

**Comment by petrovska-petro** [comment]
gelato confirmation for off-chain estimate calling non-view method is alright 

<img width="878" alt="Screenshot 2022-09-09 at 13 52 21" src="https://user-images.githubusercontent.com/84875062/189343897-bbe41a2c-d58b-4329-b1c6-7f26466c3542.png">

**Comment by shuklaayush** [comment]
CL says that `checkUpkeep` which isn't view should be fine
<img width="507" alt="image" src="https://user-images.githubusercontent.com/27727946/190478276-7ffec33a-7ee2-41e1-9468-2f53c92bf7f0.png">

**Comment by petrovska-petro** [comment]
### Keepers jobs registration links

[cl link](https://automation.chain.link/mainnet/62741682725873343636192365768984916220959346265157745745427912784419725183541)

[gelato link](https://app.gelato.network/task/0x4334b4a5ca3f4177575d15be2296dedc352aa4b042cfd5ea32ae08bd2abb279e?chainId=1)


### Findings on the setup

In the gelato infra we founded that the execload given back by the checkup needs to follow another format, which makes it incompatible with CL, since our intention was to keep the compatibility with both keepers infra for the testing.

Needs to be the following:

```
performData_ = abi.encodeWithSelector(performUpkeep.selector, getAuraPriceInUsdSpot(totalAura));
```

instead of:

```
performData_ = abi.encode(getAuraPriceInUsdSpot(totalAura));
```

Since their SC is checking that the selector to make sure that they're executing the right selector we specified in the task id

**Comment by petrovska-petro** [comment]
1st keeper harvest [tx](https://etherscan.io/tx/0xb559fb7360d55bf311666b94e1b41aa94a6aaadcd1f34ffdd305b9e765da5df9)

**Comment by petrovska-petro** [comment]
reminder to myself to revisit after treasury decision to update contract logic to reflect it

**Comment by petrovska-petro** [comment]
latest deployment setup:

- [logic](https://etherscan.io/address/0x1b84d5b58485dd4504ae19bf42a277c57d26f081)
- [proxy](https://etherscan.io/address/0x3ae662c14395b7d54695a7919e7ce7914a040a01)

**Comment by petrovska-petro** [comment]
cancellation of old upkeep [tx](https://etherscan.io/tx/0x4408e0fbb6b0f2d60255f1661c01c0d22cd684289098b04352fc2544cf13887d)

funds wd from old upkeep [tx](https://etherscan.io/tx/0x62ef32fc5c8574ac7e3394f157a1db8fd7af210b8f72e13e26cc76c168f35ffc)

**Comment by petrovska-petro** [comment]
new upkeep registration [tx](https://etherscan.io/tx/0xe75fced93be42e7ae316e2693711c8b9e6325b401dc8e653ba4a7098c7d580ce)

**Comment by petrovska-petro** [comment]
Closing this ticket as the initial release has being merged and sent for review. In favour of tracking security concerns in #24
