### ISSUE TITLE
remove status struct and `.keeper()` asserts to make compatible with any contract

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-avatars#22]
> - consider removing status struct and calls to save gas
> - consider removing `.keeper()` asserts in order to make this contract generally usable for all of our upkeeps

_Originally posted by @gosuto-inzasheru in https://github.com/Badger-Finance/badger-avatars/issues/16#issuecomment-1348280712_

**Comment by petrovska-petro** [comment]
handled in #16
