### ISSUE TITLE
validate to be registered contract has check and perform upkeep selectors

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-avatars#23]
<img width="892" alt="Screenshot 2022-12-14 at 13 18 49" src="https://user-images.githubusercontent.com/2835259/207536670-6e32af31-7829-499a-9f3f-052018c9d620.png">

**Comment by petrovska-petro** [comment]
have not found a reliable manner to determine this on-chain, which leads me to think why they opted themselves as well to handle in the f/e level

always we should assume that contract B, could have fallback, when identifiers do not match the targeted. In our case, we will have the contract to go thru the msig repo thru a 2/n review, which could behave as similar as their f/e check-up at the end of the day

@gosuto-inzasheru lmk your thoughts or if you aware of a reliable on-chain way to handle it

**Comment by gosuto-inzasheru** [comment]
what do you mean by "that contract B, could have fallback"? as in the check and perform upkeep functions are called from the fallback function, and are therefore not visible as a function in the contract itself?

**Comment by petrovska-petro** [comment]
> what do you mean by "that contract B, could have fallback"? as in the check and perform upkeep functions are called from the fallback function, and are therefore not visible as a function in the contract itself?

was referring to the case that could not find an on chain way to verify that those methods exists reliably. so adding a contract as a member, we should assume that could have a fallback method, which could get trigger if for example performupkeep does not exist and the content of the fallback being malicious

**Comment by petrovska-petro** [comment]
closing since it has being integrated https://github.com/Badger-Finance/badger-multisig/issues/1133
